version: "0.2"
ignorePaths:
  - .gitignore
  - dockerfile
  - compose.yaml
  - src/entities
  - .env.prod.example
  - .env.dev.example
  - .env.prod
  - .env.dev
  - .dockerignore
  - assets/emails/budget.html
  - assets/emails/password.html
dictionaryDefinitions: []
dictionaries: []
words:
  - Aços
  - actix
  - chrono
  - cnpj
  - CPNJ
  - cust
  - dotenv
  - Ferros
  - httpauth
  - ilike
  - intoval
  - jsonwebtoken
  - lettre
  - luma
  - Orçamento
  - printpdf
  - Redefinição
  - Senha
  - serde
  - singlepart
  - sqlx
  - typst
  - unaccent
  - xlsxwriter
ignoreWords: []
import: []
