version: "0.2"
ignorePaths:
  - .gitignore
  - dockerfile
  - compose.yaml
  - src/entities 
  - .env.prod.example
  - .env.dev.example
  - .env.prod
  - .env.dev
  - .dockerignore
dictionaryDefinitions: []
dictionaries: []
words:
  - Aços
  - actix
  - chrono
  - cnpj
  - CPNJ
  - cust
  - dotenv
  - Ferros
  - httpauth
  - ilike
  - intoval
  - jsonwebtoken
  - luma
  - printpdf
  - serde
  - sqlx
  - typst
  - unaccent
  - xlsxwriter
ignoreWords: []
import: []
