version: "0.2"
ignorePaths:
  - .gitignore
  - dockerfile
  - compose.yaml
  - src/entities
  - .env
  - .example.env
  - .dockerignore
dictionaryDefinitions: []
dictionaries: []
words:
  - actix
  - chrono
  - dotenv
  - httpauth
  - intoval
  - jsonwebtoken
  - printpdf
  - serde
  - sqlx
  - typst
  - xlsxwriter
ignoreWords: []
import: []
