//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::ClientType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "clients")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub phone: String,
    pub client_type: ClientType,
    pub cpf: Option<String>,
    pub cnpj: Option<String>,
    pub observation: Option<String>,
    pub blocked: bool,
    pub zipcode: String,
    pub state: String,
    pub city: String,
    pub street: String,
    pub complement: Option<String>,
    pub neighborhood: Option<String>,
    pub number: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::budgets::Entity")]
    Budgets,
}

impl Related<super::budgets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Budgets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
