//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "images")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub file_name: String,
    #[sea_orm(unique)]
    pub path: String,
    pub mime_type: Option<String>,
    pub size: i64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::brands::Entity")]
    Brands,
    #[sea_orm(has_many = "super::products_images::Entity")]
    ProductsImages,
}

impl Related<super::brands::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Brands.def()
    }
}

impl Related<super::products_images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductsImages.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
