//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod brands;
pub mod brands_images;
pub mod budgets;
pub mod classes;
pub mod clients;
pub mod images;
pub mod products;
pub mod products_images;
pub mod reset_password_tokens;
pub mod roles;
pub mod sea_orm_active_enums;
pub mod types;
pub mod users;
