//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0
#![allow(unused_imports)]
pub use super::brands::Entity as Brands;
pub use super::classes::Entity as Classes;
pub use super::images::Entity as Images;
pub use super::products::Entity as Products;
pub use super::products_images::Entity as ProductsImages;
pub use super::roles::Entity as Roles;
pub use super::types::Entity as Types;
pub use super::users::Entity as Users;
