//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "products")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: String,
    pub description: String,
    pub type_id: Option<Uuid>,
    pub class_id: Option<Uuid>,
    pub blocked: bool,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub price_kg: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub price_kg_no_cut: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub price_kg_cut: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub price_3mt: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub price_br: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub price_rod: Decimal,
    #[sea_orm(column_type = "Double")]
    pub weight_3mts: f64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::classes::Entity",
        from = "Column::ClassId",
        to = "super::classes::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Classes,
    #[sea_orm(has_many = "super::products_images::Entity")]
    ProductsImages,
    #[sea_orm(
        belongs_to = "super::types::Entity",
        from = "Column::TypeId",
        to = "super::types::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Types,
}

impl Related<super::classes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Classes.def()
    }
}

impl Related<super::products_images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductsImages.def()
    }
}

impl Related<super::types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Types.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
