//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "products")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub code: String,
    pub description: String,
    pub type_id: Option<Uuid>,
    pub class_id: Option<Uuid>,
    pub blocked: bool,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub price_kg: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub price_kg_no_cut: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub price_kg_cut: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub price_3mt: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub price_br: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub price_rod: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub weight_3mts: Option<Decimal>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub brand_id: Option<Uuid>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub price_p_mt: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub cut_percentage: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((12, 6)))", nullable)]
    pub weight_p_mm: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 3)))", nullable)]
    pub weight: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 3)))", nullable)]
    pub weight_esp: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 3)))", nullable)]
    pub weight_p_br: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub br_price: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::brands::Entity",
        from = "Column::BrandId",
        to = "super::brands::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Brands,
    #[sea_orm(
        belongs_to = "super::classes::Entity",
        from = "Column::ClassId",
        to = "super::classes::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Classes,
    #[sea_orm(has_many = "super::products_images::Entity")]
    ProductsImages,
    #[sea_orm(
        belongs_to = "super::types::Entity",
        from = "Column::TypeId",
        to = "super::types::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Types,
}

impl Related<super::brands::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Brands.def()
    }
}

impl Related<super::classes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Classes.def()
    }
}

impl Related<super::products_images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductsImages.def()
    }
}

impl Related<super::types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Types.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
