//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "client_type")]
pub enum ClientType {
    #[sea_orm(string_value = "pf")]
    Pf,
    #[sea_orm(string_value = "pj")]
    Pj,
}
