# Generated by Django 4.2.19 on 2025-04-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jb', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='weight_kg_no_cut',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
